### ISSUE TITLE
Error when importing clipperpy

### ISSUE THREAD

**Issue by Guo-hk** [HKUST-Aerial-Robotics/MonoLaneMapping#1]
Hello, thank you for the excellent work:

I try to run the demo_mapping but I'm getting this import error:
ModuleNotFoundError: No module named 'clipperpy.clipperpy'

I have already installed it according to [the official instructions of Clipper](https://github.com/qiaozhijian/clipper).
I am using the Python 3.7 environment from Anaconda.

Thank you so much！

**Comment by qiaozhijian** [comment]
Maybe I didn't merge the newest version of the official repository. I have done it now.
