### ISSUE TITLE
请教一下控制点初值的设置是否过于复杂？

### ISSUE THREAD

**Issue by shaoxiaodong92** [HKUST-Aerial-Robotics/MonoLaneMapping#11]
按论文中设计主要能解决那些case？
如果直接根据弦长法（chord length），例如先对车道线长度进行计算（可以先用三次曲线拟合，再采样，完成长度计算），然后等间距（例如3m），选择控制点初值；考虑到感知误差和定位的飘移，要求选择控制点的初值周围，原始点足够密集，以这种方式，又会有什么问题呢 ？

**Comment by shaoxiaodong92** [comment]
lane_opt.py 95行 `ctrl_pts, u, error = lm.ctrl_pts.find_footpoint(pt_w)` ; u完成计算， 和 pt_w 绑定后，后续进行isam迭代优化过程中u不会进行更新，但控制点每次迭代都在更新，每次迭代不需要重新计算u吗? 还是我对isam理解有问题，它内部只进行了一次迭代 ？

**Comment by qiaozhijian** [comment]
> 按论文中设计主要能解决那些case？ 如果直接根据弦长法（chord length），例如先对车道线长度进行计算（可以先用三次曲线拟合，再采样，完成长度计算），然后等间距（例如3m），选择控制点初值；考虑到感知误差和定位的飘移，要求选择控制点的初值周围，原始点足够密集，以这种方式，又会有什么问题呢 ？

1. 在车道线检测噪声不大的情况下，没有问题。比如给的示例中，车道线检测是网络的输出结果，几乎没啥噪声。但是在众包场景下，一条车道线拥有多个视角的观测，车道线点云太杂乱，就难以用弦长法+等间距的方法解决问题。
2. 对于三次曲线来说，该表达式是一个单射，比如一个x只能对应一个y，但对于环岛，或者曲率大的路段来说，一个x可能会对应多个y。针对这种情况，样条表示是更好的选择。当然，你也可以分段三次曲线拟合，没问题，本身解决问题的方法就不止一种。

**Comment by qiaozhijian** [comment]
> lane_opt.py 95行 `ctrl_pts, u, error = lm.ctrl_pts.find_footpoint(pt_w)` ; u完成计算， 和 pt_w 绑定后，后续进行isam迭代优化过程中u不会进行更新，但控制点每次迭代都在更新，每次迭代不需要重新计算u吗? 还是我对isam理解有问题，它内部只进行了一次迭代 ？

理论上要更新，就像ICP一样，是一个EM过程。您可以比较一下更不更新的区别，如果更新了效果提升不大，也可以不更新，

**Comment by shaoxiaodong92** [comment]
感谢解答
