### ISSUE TITLE
About OpenLane Datesets

### ISSUE THREAD

**Issue by goodgoodliving** [HKUST-Aerial-Robotics/MonoLaneMapping#12]
Is the provided dataset missing? Upon downloading the provided dataset, I noticed that there are only two subdirectories inside the folder, 'rosbag' and 'test', and the 'training' and 'validation' directories are missing, resulting in the following error:
ileNotFoundError: [Errno 2] No such file or directory: '/home/ly/LaneMapping/catkin_ws/src/MonoLaneMapping/datasets/OpenLane/lane3d_1000/validation/segment-10203656353524179475_7625_000_7645_000_with_camera_labels/152268801497018700.json'
INFO - 2023-09-23 22:21:51,005 - core - signal_shutdown [atexit]

**Comment by goodgoodliving** [comment]
When I ran the first command as per 'Reproduce the results in the paper,' I encountered the aforementioned error.

**Comment by qiaozhijian** [comment]
Yes. If you want to reproduce the results, you should download the original complete OpenLane dataset.
