### ISSUE TITLE
请教运行mapping_bm.py时出现的error

### ISSUE THREAD

**Issue by Nick-0814** [HKUST-Aerial-Robotics/MonoLaneMapping#14]
乔博您好！我是SLAM方向的一名研一新生。
  我有一个关于运行mapping_bm.py时出现的错误的问题(python examples/mapping_bm.py--cfg_file=config/lane_mapping.yaml)。
代码报错如下：
File "/home/liu/anaconda3/envs/pytorch/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "examples/mapping_bm.py", line 23, in run_segments
    lane_mapper = LaneMapping(bag_path)
  File "/home/liu/catkin_ws/src/MonoLaneMapping/lane_slam/system/lane_mapping.py", line 17, in __init__
    self.load_data()
  File "/home/liu/catkin_ws/src/MonoLaneMapping/lane_slam/system/lane_ui.py", line 215, in load_data
    lanes_predict = self.preprocess_lanes(lanes_predict)
  File "/home/liu/catkin_ws/src/MonoLaneMapping/lane_slam/system/lane_ui.py", line 230, in preprocess_lanes
    xyz = points_downsample(xyz, self.pp_ds)
  File "/home/liu/catkin_ws/src/MonoLaneMapping/lane_slam/lane_utils.py", line 77, in points_downsample
    has_points = np.zeros((math.ceil((max_x - min_x) / size) + 1,
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 47.3 GiB for an array with shape (187, 4737, 7162) and data type float64
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/mapping_bm.py", line 105, in <module>
    main(bag_files)
  File "examples/mapping_bm.py", line 49, in main
    result = run_all_segments(bag_paths, multi_process=not cfg.visualization)
  File "examples/mapping_bm.py", line 42, in run_all_segments
    result.update(res.get())
  File "/home/liu/anaconda3/envs/pytorch/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
numpy.core._exceptions.MemoryError: Unable to allocate 47.3 GiB for an array with shape (187, 4737, 7162) and data type float64

  这似乎是numpy数组出现了问题。
  我想问一下您，我该如何解决这个问题？
  无意打扰，望您回复！
![issue](https://github.com/HKUST-Aerial-Robotics/MonoLaneMapping/assets/111438180/cefd2706-b392-4c4a-9a6a-8db49f8cf593)

**Comment by qiaozhijian** [comment]
您好。看报错好像是内存不够。因为我是一下子评估整个数据集，所以把所有segments的结果都保存到一个数组里，最后评估。也许你可以试试在一个数据集被处理完之后，把它保存到文件里。然后另行运行评估代码，读取文件，进行评估。

**Comment by theyunfeng** [comment]
> 您好。看报错好像是内存不够。因为我是一下子评估整个数据集，所以把所有segments的结果都保存到一个数组里，最后评估。也许你可以试试在一个数据集被处理完之后，把它保存到文件里。然后另行运行评估代码，读取文件，进行评估。

乔博你好，我也因为内存问题所以用examples/demo_mapping.py 分别跑了一下您提供的rosbag文件夹中的一些数据，发现可能效果不是很理想，如图
![image](https://github.com/HKUST-Aerial-Robotics/MonoLaneMapping/assets/91672632/58b5def7-5d88-4b9b-971d-0495b494d48d)

，请问demo_mapping.py 和mapping_bm.py在做数据处理和优化时存在很大差别吗？如果使用mapping_bm.py的话效果会好很多吗？

**Comment by qiaozhijian** [comment]
> > 您好。看报错好像是内存不够。因为我是一下子评估整个数据集，所以把所有segments的结果都保存到一个数组里，最后评估。也许你可以试试在一个数据集被处理完之后，把它保存到文件里。然后另行运行评估代码，读取文件，进行评估。
> 
> 乔博你好，我也因为内存问题所以用examples/demo_mapping.py 分别跑了一下您提供的rosbag文件夹中的一些数据，发现可能效果不是很理想，如图 ![image](https://private-user-images.githubusercontent.com/91672632/296943361-58b5def7-5d88-4b9b-971d-0495b494d48d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTMwMjksIm5iZiI6MTcwNTM5MjcyOSwicGF0aCI6Ii85MTY3MjYzMi8yOTY5NDMzNjEtNThiNWRlZjctNWQ4OC00YjliLTk3MWQtMDQ5NWI0OTRkNDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA4MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZTRkNTgzZjRmZjg3ZmVmOTllNGE5NmUyN2Q4ZDRmMWFkYWFhYmEyZDMzYWNmZTQyYTVkNTI5YmYxNWEwMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7GSnXA288mzGkEbA-dH19tsxj4n7eLDBo9nfSd5AMMw)
> 
> ，请问demo_mapping.py 和mapping_bm.py在做数据处理和优化时存在很大差别吗？如果使用mapping_bm.py的话效果会好很多吗？

这两个py的代码是一样的。你的这个例子找的很好，精准体现了该算法目前的一些问题。这个问题是由于网络输出的车道线检测太过于奇怪，导致建图模块输出的结果也很奇怪。

**Comment by Nick-0814** [comment]
乔博,您好.我正在尝试使用您开源的代码进行实时建图.看了您的代码中的优化部分,每次优化是对当前帧中所含车道线的所有控制点进行优化.那么随着车道线的延长,优化速度会越来越慢.那么请问有什么好的思路进行实时建图.

**Comment by qiaozhijian** [comment]
> 乔博,您好.我正在尝试使用您开源的代码进行实时建图.看了您的代码中的优化部分,每次优化是对当前帧中所含车道线的所有控制点进行优化.那么随着车道线的延长,优化速度会越来越慢.那么请问有什么好的思路进行实时建图.

你说的没有错，优化是会越来越慢的。我建议就不用因子图了。位姿不优化，认为里程计提供的很准。然后剩下就按曲线拟合去做。

**Comment by sharknow** [comment]
> > 乔博,您好.我正在尝试使用您开源的代码进行实时建图.看了您的代码中的优化部分,每次优化是对当前帧中所含车道线的所有控制点进行优化.那么随着车道线的延长,优化速度会越来越慢.那么请问有什么好的思路进行实时建图.
> 
> 你说的没有错，优化是会越来越慢的。我建议就不用因子图了。位姿不优化，认为里程计提供的很准。然后剩下就按曲线拟合去做。

作者您好，请问，里程计是慢慢在漂的吧，为什么可以认为里程计提供的很准呀？

**Comment by qiaozhijian** [comment]
> > > 乔博,您好.我正在尝试使用您开源的代码进行实时建图.看了您的代码中的优化部分,每次优化是对当前帧中所含车道线的所有控制点进行优化.那么随着车道线的延长,优化速度会越来越慢.那么请问有什么好的思路进行实时建图.
> > 
> > 
> > 你说的没有错，优化是会越来越慢的。我建议就不用因子图了。位姿不优化，认为里程计提供的很准。然后剩下就按曲线拟合去做。
> 
> 作者您好，请问，里程计是慢慢在漂的吧，为什么可以认为里程计提供的很准呀？

里程计由VIO提供，一般认为很准。车道线往往只能提供横向约束。另外，这是nuscenes数据集，我默认用里程计真值，肯定很准。nuscene很难跑VIO，所以我在论文里通过加位姿噪声模拟不准的里程计。

**Comment by sharknow** [comment]
> > > > 乔博,您好.我正在尝试使用您开源的代码进行实时建图.看了您的代码中的优化部分,每次优化是对当前帧中所含车道线的所有控制点进行优化.那么随着车道线的延长,优化速度会越来越慢.那么请问有什么好的思路进行实时建图.
> > > 
> > > 
> > > 你说的没有错，优化是会越来越慢的。我建议就不用因子图了。位姿不优化，认为里程计提供的很准。然后剩下就按曲线拟合去做。
> > 
> > 
> > 作者您好，请问，里程计是慢慢在漂的吧，为什么可以认为里程计提供的很准呀？
> 
> 里程计由VIO提供，一般认为很准。车道线往往只能提供横向约束。另外，这是nuscenes数据集，我默认用里程计真值，肯定很准。nuscene很难跑VIO，所以我在论文里通过加位姿噪声模拟不准的里程计。

谢谢
