### ISSUE TITLE
对论文中的伪代码有些疑问 (`||V_0 - P.head||_2 <= ||V_0 - P.tail||_2`)

### ISSUE THREAD

**Issue by LiuJingCheng6** [HKUST-Aerial-Robotics/MonoLaneMapping#15]
作者您好，阅读您的论文时，在伪代码中发现一个判断条件不太理解，已用红色标出，这个条件好像是始终成立的，是否写错了
![image](https://github.com/HKUST-Aerial-Robotics/MonoLaneMapping/assets/103499236/a3fc8c29-f86b-4d94-8541-4f309285c3d5)

**Comment by qiaozhijian** [comment]
啊。。。实在是不好意思，没想到在论文里有这么低级的错误。应该是||V0-head||<||V0-tail|，用于判断是要在头部延伸还是尾部延伸|
Ah... I am really sorry, I didn't expect such a basic error in the paper. It should be `||V0 - head|| < ||V0 - tail||`, which is used to determine whether to extend at the head or the tail.

**Comment by LiuJingCheng6** [comment]
谢谢解答！
