### ISSUE TITLE
控制点选择的一些问题 (the points beyond these two normal planes)

### ISSUE THREAD

**Issue by LiuJingCheng6** [HKUST-Aerial-Robotics/MonoLaneMapping#16]
![image](https://github.com/HKUST-Aerial-Robotics/MonoLaneMapping/assets/103499236/cd2822ea-35a8-438d-8146-119027bf0d45)
作者您好，您在论文里提出对控制点进行扩展时，选取的是the points beyond these two normal planes，从这个示意图中没有理解您的意思，请问这个条件是如何判断的，谢谢！
Hello author, in your paper, you mentioned that when extending the control points, you select "the points beyond these two normal planes." I did not understand your meaning from the diagram provided. Could you please explain how this condition is determined? Thank you!

**Comment by qiaozhijian** [comment]
样条的延展和初始化用的算法本质是一样的。我们可以把初始化看成随机初始化一点，然后进行延展。
我把这个问题看成给定一个控制点集合，一堆无序散点，如何延展控制点的问题。
1. 首先，控制点是有序的，法平面的法向量平行于样条上该点的切线。首末两个控制点的法平面夹住的测量点，我们是不考虑它们作为延展的。
2. 对于剩下的测量点，我们用之前拟合多项式用于延展。新加入点被建模成，以端点（首点或末点）为中心，期望控制点间距为半径的球与多项式的交点。
3. 求一个球和三次多项式的交点这个方程不好解，因此我们设计了一个启发式的迭代的算法去求交点。这个在理论上的保证是，球是一个凸集，如果多项式局部也是个凸集，那凸集之间相互映射，就可以得到交点（Alternating projection）。
4. 得到交点后，我们可以更新首末点，然后重复“去除不被用于延展的测量点”和“延展新控制点”两个步骤，知道所有测量点都被用于延展。

The algorithms used for the extension and initialization of splines are essentially the same. We can consider initialization as randomly initializing a point and then extending it.
I view this problem as being given a set of control points, a bunch of unordered scatter points, how to extend the control points.

1. First, the control points are ordered, and the normal vector of the law plane is parallel to the tangent at that point on the spline. The measured points clamped by the law planes of the first and last control points are not considered for extension.

2. For the remaining measured points, we use the previously fitted polynomial for extension. New points are modeled as the intersection of a sphere centered at an endpoint (either the first or last point) with the radius being the desired control point spacing and the polynomial.

3. Solving for the intersection of a sphere and a cubic polynomial is not straightforward, so we designed a heuristic iterative algorithm to find the intersection. The theoretical guarantee here is that if the sphere is a convex set and the polynomial is locally convex, then by mapping the convex sets to each other, an intersection point can be obtained (Alternating projection).

4. After obtaining the intersection point, we can update the endpoints and then repeat the steps of "removing measured points not used for extension" and "extending the new control points" until all measured points have been used for extension.

**Comment by LiuJingCheng6** [comment]
谢谢解答！
