### ISSUE TITLE
assert self.n <= self.m

### ISSUE THREAD

**Issue by HCHrobo** [HKUST-Aerial-Robotics/MonoLaneMapping#19]
你好，有个关于kmmatcher实现的问题想请教一下，这个断言n<=m，即landmark要小于当前的detection，

1. 为何要特殊指定这个size判断呢，如果出现遮挡可能会有landmark对应不到detection
2. 如果出现了实例大于观测的情况，需要怎么特殊处理么

#max weight assignment
class KMMatcher:

    ## weights : nxm weight matrix (numpy , float), n <= m
    def __init__(self, weights):
        weights = np.array(weights).astype(np.float32)
        self.weights = weights
        self.n, self.m = weights.shape
        assert self.n <= self.m

**Comment by HCHrobo** [comment]
我发现如果数据self.n <= self.m，求解可能会出现异常，我尝试将weights转置后，可以求解出配对，然后将landmark和detection的id互换也可以

**Comment by qiaozhijian** [comment]
> 我发现如果数据self.n <= self.m，求解可能会出现异常，我尝试将weights转置后，可以求解出配对，然后将landmark和detection的id互换也可以

请问你的意思是通过交换landmark和detection就可以解决问题，是吗？

**Comment by HCHrobo** [comment]
对的，就是关联矩阵行列互换，然后关联的pair最后再调整一下好像就可以了，只是不确定是否有理论验证是正确的…
