### ISSUE TITLE
请教一下关于首尾控制点的问题

### ISSUE THREAD

**Issue by jason-yspjf** [HKUST-Aerial-Robotics/MonoLaneMapping#20]
大佬您好，有两个疑问，麻烦解答下
1.假设现在有N个控制点，现在对于前4个控制点（A，B，C，D）进行采样，那么得到的采样点其实是在BC段内，对于最后4个控制点（W，X，Y，Z）也一样，采样后的点是在XY段内，那该怎么获取AB段和YZ段内的采样点，也就是说为了获取车道线采样点的完整性，是否需要对首尾控制点进行拓展？
2.在您的代码中其实是存在对于控制点padding的逻辑的（当控制点数量<4时），但我理解只是对控制点根据之前或者之后的两个控制点的方向向量进行了延长？不知道这样理解是否正确，以及这么做的理论依据是什么呢

**Comment by qiaozhijian** [comment]
您好
1. 你可以看find_footpoint函数，AB和YZ我没有管他，你可以当成线段处理，而不是样条。你也可以尝试拓展，请查看这个文档 [catmullRom](https://www.cs.cmu.edu/~fp/courses/graphics/asst5/catmullRom.pdf) ，如果你拟合A和Z的切线，是可以扩展的。
2. 这方面没有什么理论依据，都是基于实际情况考虑，设计一些规则。我默认控制点是均匀长度的，如果太少的话，那说明车道线不够长，你可以用更短的距离去放置控制点，也可以用折线近似。
