### ISSUE TITLE
Could you please comment on why decoupling the pose update with the spline smoothing?

### ISSUE THREAD

**Issue by farocean97** [HKUST-Aerial-Robotics/MonoLaneMapping#22]
In the paper, the pose update and spline control points optimization are drawn in the same factor graph, but the system diagram and actual implementation chooses to decouple these two. Do you mind share if there are any issues solving them togehter?
https://github.com/HKUST-Aerial-Robotics/MonoLaneMapping/blob/647ba8907ec05be820705d0455e0c066444e4dc1/lane_slam/system/lane_opt.py#L70

**Comment by qiaozhijian** [comment]
I decouple them in the paper as well (see Fig. 2).

Yes, there may be some issues. We don't have visual feature points and IMU factors, but only lane line factors. However, there are two issues in this situation. 

1. First, the lane line factor is based on point-to-curve data association, which relies on nearest-neighbor searches — meaning that when the pose is inaccurate, this association could be wrong. Although you can update the pose and the data association simultaneously using an ICP-like method, I've tried this approach, and it does not work. I believe the reason may be the second issue. 
2. That is, lane line factors do not provide a complete constraint on the pose, and most of the time, the pose estimation is degenerate. Therefore, I separated them. But this does not fully improve the degeneracy problem. 

To fundamentally solve this issue, we need to estimate the direction of pose degeneracy and avoid updating in this direction, or we need to introduce more constraints, such as from IMU and visual feature points.
