### ISSUE TITLE
question about complex curves

### ISSUE THREAD

**Issue by yuxuanzhou97** [HKUST-Aerial-Robotics/MonoLaneMapping#24]
Hello! Thank you for the great work, which is so inspring!

I wonder if the online mapping algorithm could handle curves with high curvature like below?

![image](https://github.com/HKUST-Aerial-Robotics/MonoLaneMapping/assets/30310862/ecdcbb7b-4f22-4c73-a20f-93140af71ffc)

**Comment by qiaozhijian** [comment]
Perhaps you need to add some tricks, such as rotating the curve by a certain angle (default is 45° in the code), or split it into segments.
