### ISSUE TITLE
what is the "annotation_dir" filed points to?

### ISSUE THREAD

**Issue by TheCuriousJoe** [HKUST-Aerial-Robotics/MonoLaneMapping#3]
I found that there is a “annotation_dir” field in "lane_association.yaml" and "lane_mapping.yaml", which points to some data. 

Is the data provided in the link [[OneDrive]](https://hkustconnect-my.sharepoint.com/:u:/g/personal/zqiaoac_connect_ust_hk/EQxCBwl1Wc5Foq1wNOJ7ZKQBrNik0GK_qa7qEed_zrbGmQ?e=bYSYvk)[[Baidu Cloud]](https://pan.baidu.com/s/1Hrd8ashoiB4_f0B-iz6OHQ?pwd=2023)? or do I need to generate it by some other method? 

This field does not seem to be required to be modified in the readme, please check.

**Comment by qiaozhijian** [comment]
It contains extrisic parameters and lane marking labels of the original dataset Openlane. It's necessary to run the code and evaluate the method. Sorry for suggesting you not to download Openlane dataset. I have modified the readme.
