### ISSUE TITLE
No results due to merge_lane operation

### ISSUE THREAD

**Issue by Guo-hk** [HKUST-Aerial-Robotics/MonoLaneMapping#4]
When I set `merge_lane` of `lane_mapping` to true, it seems that the system doesn't produce any results. 
Should the condition `lm.obs_num < 10` be removed in the `post_merge_lane` function because initially the observation count won't satisfy this condition, causing `lane_in_map` to be continuously deleted?

**Comment by qiaozhijian** [comment]
You run the demo_mapping.py and have this result?

**Comment by Guo-hk** [comment]
Yes, I ran the demo_mapping.py.

**Comment by qiaozhijian** [comment]
Thank you. I have fixed this bug. If you have better solution, welcome to contribute to this repo.
