### ISSUE TITLE
question about rosbag

### ISSUE THREAD

**Issue by wo712268** [HKUST-Aerial-Robotics/MonoLaneMapping#7]
Hello! Thank you for your work!

I feel confused when i use the rosbag, the msg lists are:

> /gt_pose_wc
> /lanes_gt
> /lanes_predict

I print the /lanes_predict and noticed that the points in each detected lane are sparse. The distance between first few points is 5 meters, and the rear is 10 meters, or even 20 meters. 

I know little about Persformer (っ °Д °;)っ, are these points sampled? Can i test my data directly with Persformer's results?

**Comment by qiaozhijian** [comment]
Thanks for your interest.
1. Yes, points are sampled in Persformer. Specifically, Persformer will sample points along with Y axis at a fixed distance and determine whether the sampled point is valid based on the predicted visibility, see [resample_laneline_in_y_with_vis](https://github.com/OpenDriveLab/PersFormer_3DLane/blob/7f7715ae17937cf8e651072a9d3bdb13a573b731/data/Load_Data.py#L2623). Maybe most points are predicted unvisiable in these cases.
2. You can't directly use results from Persformer for two reasons:
    + you should transform the coordinate system, referring to [transform_persformer_to_openlane](https://github.com/qiaozhijian/openlane_bag/blob/e0ae18c52c8fbbd44b9c0f4023dca1c5cabfac18/utils/waymo_bag_writer.py#L60)
    + you need odometry between two frames, which can be obtained by VIO or GT poses.

**Comment by wo712268** [comment]
> Thanks for your interest.
> 
> 1. Yes, points are sampled in Persformer. Specifically, Persformer will sample points along with Y axis at a fixed distance and determine whether the sampled point is valid based on the predicted visibility, see [resample_laneline_in_y_with_vis](https://github.com/OpenDriveLab/PersFormer_3DLane/blob/7f7715ae17937cf8e651072a9d3bdb13a573b731/data/Load_Data.py#L2623). Maybe most points are predicted unvisiable in these cases.
> 2. You can't directly use results from Persformer for two reasons:
>    
>    * you should transform the coordinate system, referring to [transform_persformer_to_openlane](https://github.com/qiaozhijian/openlane_bag/blob/e0ae18c52c8fbbd44b9c0f4023dca1c5cabfac18/utils/waymo_bag_writer.py#L60)
>    * you need odometry between two frames, which can be obtained by VIO or GT poses.

Thank you for your reply! I have odometry pose which is from VINS, thank you! \(@^0^@)/

**Comment by bitwangdan** [comment]
@qiaozhijian Hi, “transform_persformer_to_openlane” , is it mapped from camera to ego?

**Comment by qiaozhijian** [comment]
> @qiaozhijian Hi, “transform_persformer_to_openlane” , is it mapped from camera to ego?

Hi, sorry for late reply. 

I'm sorry whether you can give the exact link to this code?

I assume you are confused about the prediction of PersfFormer. According to [this issue](https://github.com/OpenDriveLab/OpenLane/issues/24), Persformer predicts xyz in the LaneNet vehicle-coord system, while the openlane GT is annotated in the camera system. So we need this transformation.
