### ISSUE TITLE
missing validation folder in dataset 

### ISSUE THREAD

**Issue by cshang412** [HKUST-Aerial-Robotics/MonoLaneMapping#8]
i download dataset from BaiduYun or OneDrive, after uncompress the dataset, here is what i got :
![图片](https://github.com/HKUST-Aerial-Robotics/MonoLaneMapping/assets/29396384/c6c99e20-53a7-4e05-9e2e-0eaa38829c1e)

At the same time i run the demo script:
`python3 examples/demo_mapping.py --cfg_file=config/lane_mapping.yaml`

i got:
![图片](https://github.com/HKUST-Aerial-Robotics/MonoLaneMapping/assets/29396384/d1be2875-1e80-4777-ba5f-ffc13f34d720)

Also for demo_curve_fitting.py，after excute  `python3 examples/demo_curve_fitting.py `:
![图片](https://github.com/HKUST-Aerial-Robotics/MonoLaneMapping/assets/29396384/decf8f7c-feb3-4c78-93a9-abba93c02af1)

**Comment by qiaozhijian** [comment]
Hi @cshang412 , thanks for trying. Maybe you should download the original OpenLane dataset (https://github.com/OpenDriveLab/OpenLane).

**Comment by qiaozhijian** [comment]
I have update the code to make sure you don't need to download OpenLane dataset to run the demo_mapping.py
