### ISSUE TITLE
lane.pcd 和 lane_selected.pcd?

### ISSUE THREAD

**Issue by hanbing123-cool** [HKUST-Aerial-Robotics/MonoLaneMapping#9]
请问运行demo_cure_fitting时候的lane.pcd 和 lane_selected.pcd是在哪里生成的？

**Comment by qiaozhijian** [comment]
Already uploaded.

**Comment by hanbing123-cool** [comment]
你好，lane.pcd中是只包含一条车道线的点云吗？lane_selected.pcd是表示控制点？，这两组数据程序中可以输出，还是你那边单独做的样例数据？

**Comment by qiaozhijian** [comment]
是的，只包含一条。没错，手动选的控制点。单独做的。

**Comment by hanbing123-cool** [comment]
好的 感谢

**Comment by hanbing123-cool** [comment]
你好，请问视频中实时建图的内容用这套代码可以实现吗?需要对代码进行怎样的更改？

**Comment by hanbing123-cool** [comment]
另外，我关闭掉里程计噪声时，发现原始位姿、优化位姿、真实位姿并没有区别，意思是说如果关闭这个选项，程序将不对位姿进行优化吗？我想利用vio跑出的位姿作为初值，然后利用车道线进行优化，那我这里是需要大概这个噪声选项然后设置合适的噪声值还是怎样？希望您能解释一下这部分内容

**Comment by qiaozhijian** [comment]
> 

可以，但要再写个rospy，发布消息给rviz

**Comment by qiaozhijian** [comment]
> 另外，我关闭掉里程计噪声时，发现原始位姿、优化位姿、真实位姿并没有区别，意思是说如果关闭这个选项，程序将不对位姿进行优化吗？我想利用vio跑出的位姿作为初值，然后利用车道线进行优化，那我这里是需要大概这个噪声选项然后设置合适的噪声值还是怎样？希望您能解释一下这部分内容

是的，默认不优化。因为车道线大多数情况下只能提供横向约束，纵向退化。gtsam python灵活性差一点，针对退化情况，我没有在这个代码里解决。但是你依然可以通过手动添加噪声，检验车道线对位姿优化的有效性以复现论文结果。如果你想用vio，我建议紧耦合，不要当初值。如果非要当初值，建议只优化未退化方向。下面有一些参考文献，希望能帮到你：
On degeneracy of optimization-based state estimation problems
X-ICP: Localizability-Aware LiDAR Registration for Robust Localization in Extreme Environments

**Comment by hanbing123-cool** [comment]
好的 好的 万分感谢

**Comment by hanbing123-cool** [comment]
在构建图模型的时候，我看代码中将odo_graph注释掉了，我想请教一下为什么这么做，同时优化控制点和位姿会存在什么问题吗？

**Comment by hanbing123-cool** [comment]
另外，由于我没有实际数据的真值，我匹配数据的时候使用原始检测点作为真值，然后插值稀疏后的作为检测点，这样是否还能进行位姿优化？因为我看到更新真值到lanes_in_map的kdtree中似乎也是构建了一个滑窗的局部地图，这样是不是可以理解为帧到局部地图的匹配优化，不知道我这样使用数据和这样理解是否正确，请您指教一下

**Comment by qiaozhijian** [comment]
> 在构建图模型的时候，我看代码中将odo_graph注释掉了，我想请教一下为什么这么做，同时优化控制点和位姿会存在什么问题吗？

没什么问题，单纯默认不优化位姿，解释见上一条回复

**Comment by qiaozhijian** [comment]
> 另外，由于我没有实际数据的真值，我匹配数据的时候使用原始检测点作为真值，然后插值稀疏后的作为检测点，这样是否还能进行位姿优化？因为我看到更新真值到lanes_in_map的kdtree中似乎也是构建了一个滑窗的局部地图，这样是不是可以理解为帧到局部地图的匹配优化，不知道我这样使用数据和这样理解是否正确，请您指教一下

我不是很理解您的第一个问题，但检测点是不能作为真值的。你可以这么理解，帧到局部地图。实际上常用的vslam流程也是这样的，如ORB-SLAM，先track frame得到初始位姿，再track map得到更准的位姿，在局部BA里更新关键帧位姿和路标点（地图）。不同的是我这个工作只是算得上一个小demo，没有做精细的系统设计，比如我没有关键帧

**Comment by hanbing123-cool** [comment]
第一个问题是说你这里使用的lanes_gt 应该是数据集中标注的结果，lanes_predict应该是检测的结果。而我目前只有检测的结果，所以我将原始的检测结果作为lanes_gt ，然后插值稀疏后的结果作为lanes_predict，然后送出程序中，我不知道这样做程序还能否有作用，是不是转化成类似帧到历史帧的匹配？

**Comment by hanbing123-cool** [comment]
我理解的就是您现在是 拿检测结果与高精地图中标注的结果 做匹配，而我目前只有检测结果，我想拿检测点与检测点的局部地图匹配，在不改动代码的情况这样是否合理

**Comment by hanbing123-cool** [comment]
我的目的是在没有真值的情况下 提升位姿定位的结果

**Comment by qiaozhijian** [comment]
这个代码就是在“拿检测点与检测点的局部地图匹配”，我觉得您设计实验可以试试您的方案

**Comment by hanbing123-cool** [comment]
好的 感谢您的回复

**Comment by theyunfeng** [comment]
> 这个代码就是在“拿检测点与检测点的局部地图匹配”，我觉得您设计实验可以试试您的方案

请问这个lanes_gt和lanes_predict分别是怎么得到的？

**Comment by qiaozhijian** [comment]
> > 这个代码就是在“拿检测点与检测点的局部地图匹配”，我觉得您设计实验可以试试您的方案
> 
> 请问这个lanes_gt和lanes_predict分别是怎么得到的？

lanes_gt是openlane数据集提供的，lane predict是我拿persformer模型预测得到的
